---
title: "Examples"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette has some example plots -- for more details on how to make a plot, see the  [how to build a chart vignette](https://vegawidget.github.io/vlbuildr/articles/articles/introduction.html) For more about the design philosophy of the package, see the [design vignette](https://vegawidget.github.io/vlbuildr/articles/design.html).

```{r }
library(vlbuildr)

vl_chart() %>%
   vl_add_data(values = mtcars) %>%
   vl_mark_point() %>%
   vl_encode_x("wt") %>%
   vl_encode_y("mpg") %>% 
   vl_encode_tooltip(c("_row","mpg","wt"))
```


```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/movies.json") %>%
  vl_encode_x(field = "IMDB_Rating", type = "quantitative") %>%
  vl_encode_y(type = "quantitative", aggregate = "count") %>%
  vl_bin_x(maxbins=10) %>%
  vl_mark_bar()
```


```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/population.json") %>%
  vl_calculate(calculate = "datum.sex == 2 ? 'Female' : 'Male'", 
               as = "gender") %>%
  vl_filter("datum.year == 2000") %>%
  vl_encode_x(field = "age", 
              type = "ordinal") %>%
  vl_encode_y(field = "people", type = "quantitative") %>%
  vl_stack_y("normalize") %>%
  vl_aggregate_y(aggregate = "sum") %>%
  vl_axis_y(title = "population") %>%
  vl_encode_color(field = "gender", type = "nominal") %>%
  vl_mark_bar() %>% 
  vl_config_axis(domainWidth = 1) %>%
  vl_config_view(stroke = "transparent")
```



```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/population.json") %>%
  vl_filter("datum.year == 2000") %>%
  vl_encode_y(field = "age", 
              type = "ordinal") %>%
  vl_encode_x(field = "people", 
              type = "quantitative", 
              aggregate = "sum",
              axis = list(title = "population"), 
              stack = "normalize") %>%
  vl_mark_bar() %>%
  vl_sort_y_by_encoding(encoding = "x")

```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_mark_tick() %>%
  vl_encode_x(field = "Horsepower", type = "quantitative") %>%
  vl_sort_x("descending")
```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_add_selection_parameter(name = "brush", select = list(type = "interval"), value = list(x = c(55,160), y = c(13,37))) %>%
  vl_mark_point() %>%
  vl_encode_x(field = "Horsepower", type = "quantitative") %>%
  vl_encode_y(field = "Miles_per_Gallon", type = "quantitative") %>%
  vl_encode_color(value = "grey") %>%
  vl_condition_color(param = "brush", field = "Cylinders", type = "ordinal")
```


```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_add_selection_parameter("org", select = c(type = "point", fields = list(list("Origin")))) %>%
  vl_bind_select_input("org", options = list(NA,"Europe","Japan","USA")) %>%
  vl_mark_point() %>%
  vl_encode_x(field = "Horsepower", type = "quantitative") %>%
  vl_encode_y(field = "Miles_per_Gallon", type = "quantitative") %>%
  vl_encode_color(value = "grey") %>%
  vl_condition_color(param = "org", field = "Cylinders", type = "ordinal")

```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_calculate(calculate = "year(datum.Year)", as = "Year") %>%
  vl_add_single_selection("CylYr", fields = list("Cylinders","Year")) %>%
  vl_bind_range_input("CylYr", "Cylinders", min = 3, max = 8, step = 1) %>%
  vl_bind_range_input("CylYr", "Year", min = 1969, max = 1981, step = 1) %>%
  vl_mark_circle() %>%
  vl_encode_x(field = "Horsepower", type = "quantitative") %>%
  vl_encode_y(field = "Miles_per_Gallon", type = "quantitative") %>%
  vl_encode_color(value = "grey") %>%
  vl_condition_color(selection = "CylYr", field = "Origin", type = "nominal") %>%
  vl_encode_size(value = 50) %>%
  vl_condition_size(selection = "CylYr", value = 100)
```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_mark_bar() %>%
  vl_encode_x(field = "Horsepower", type = "quantitative") %>%
  vl_bin_x(maxbins = 15) %>%
  vl_encode_y(aggregate = "count", type = "quantitative") %>%
  vl_facet_row(field = "Origin", type = "nominal")
```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_mark_bar() %>%
  vl_encode_x(field = list(`repeat` = "repeat"), type = "quantitative", bin = TRUE) %>%
  vl_encode_y(aggregate = "count", type = "quantitative") %>%
  vl_encode_color(field = "Origin", type = "nominal") %>%
  vl_repeat_wrap("Horsepower", "Miles_per_Gallon", "Acceleration", "Displacement")
```


```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/population.json") %>%
  vl_filter("datum.year == 2000") %>%
  vl_calculate(as = "gender", calculate = 'datum.sex == 2 ? "Female" : "Male"') %>%
  vl_encode_x(field = "gender", type = "nominal") %>%
  vl_encode_y(field = "people", type = "quantitative", aggregate = "sum") %>%
  vl_encode_color(field = "gender", type = "nominal") %>%
  vl_scale_color(range = c("#EA98D2", "#659CCA")) %>%
  vl_encode_column(field = "age", type = "ordinal", spacing = 10) %>%
  vl_remove_axis_x() %>%
  vl_axis_y(title = "population", grid = FALSE) %>%
  vl_config_view(strokeWidth = 0) %>%
  vl_mark_bar()%>% 
  vl_config_axis(domainWidth = 1) %>%
  vl_config_view(stroke = "transparent") %>%
  vl_add_properties(width = 10)
```

```{r}
bar_chart <- vl_chart() %>%
  vl_mark_bar() %>%
  vl_encode_x(field = "date:O", timeUnit = "month") %>%
  vl_encode_y(field = "precipitation:Q", aggregate = "mean")

point_chart <- vl_chart() %>%
  vl_mark_point() %>%
  vl_encode_x(field = "temp_min:Q", bin = TRUE) %>%
  vl_encode_y(field = "temp_max:Q", bin = TRUE) %>%
  vl_encode_size(aggregate = "count", type = "quantitative")
  
vl_hconcat(bar_chart, point_chart) %>% 
  vl_add_data(url = "https://vega.github.io/vega-lite/data/weather.csv") %>%
  vl_filter("datum.location === 'Seattle'")
```

```{r}
(bar_chart | point_chart) %>% 
  vl_add_data(url = "https://vega.github.io/vega-lite/data/weather.csv") %>%
  vl_filter("datum.location === 'Seattle'")
```


```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_mark_point() %>%
  vl_encode_x(field = list("repeat" = "column"), type = "quantitative") %>%
  vl_encode_y(field = list("repeat" = "row"), type = "quantitative") %>%
  vl_add_interval_selection("brush", resolve = "global") %>%
  vl_encode_color(value = "grey") %>%
  vl_condition_color(selection = "brush", field = "Origin", type = "nominal") %>%
  vl_repeat_row("Horsepower", "Acceleration", "Miles_per_Gallon") %>%
  vl_repeat_col("Miles_per_Gallon", "Acceleration", "Horsepower")
```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_mark_point() %>%
  vl_encode_x(field = "Horsepower", type = "quantitative") %>%
  vl_encode_y(field = "Miles_per_Gallon", type = "quantitative") %>%
  vl_encode_color(field = list("repeat" = "column"), type = "nominal") %>%
  vl_repeat_col("Origin", "Cylinders") %>%
  vl_resolve_scale_color("independent")
```

```{r}
vl_chart() %>%
  vl_add_data(url = "https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_filter("datum.Miles_per_Gallon !== null") %>%
  vl_timeunit(timeUnit = "year", field = "Year", as = "year") %>%
  vl_window(window = list(vl$Window(op = "mean", field = "Miles_per_Gallon", as = "Average_MPG")),
              sort = list(vl$SortField(field = "year", order = "ascending")),
              ignorePeers = FALSE, frame = list(NA,0)) %>%
  vl_encode_x(field = "Year", timeUnit = "year", type = "temporal") %>%
  vl_encode_y(field = "Average_MPG", type = "quantitative") %>% 
  vl_mark_line()
```


```{r}
heatmap <- vl_chart() %>%
  vl_encode_color(aggregate = "count", type = "Q") %>%
  vl_scale_color(scheme = "darkred") %>%
  vl_encode_x(field = "Cylinders:O") %>%
  vl_scale_x(paddingInner = 0) %>%
  vl_encode_y(field = "Year:O") %>%
  vl_scale_x(paddingInner = 0) %>%
  vl_mark_rect()

text <- vl_chart() %>%
  vl_encode_color(value = "white") %>%
  vl_encode_x(field = "Cylinders:O") %>%
  vl_encode_y(field = "Year:O") %>%
  vl_encode_text(aggregate = "count", type = "Q") %>%
  vl_mark_text(baseline = "middle")

vl_layer(heatmap, text) %>%
  vl_add_data_url("https://vega.github.io/vega-editor/app/data/cars.json") %>%
  vl_facet_column(field = "Origin", type = "nominal") 
```

